version: "3"
services:
  admin:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: docker-raect:v1
    restart: always # 自动重启
    ports:
      - 9003:80
    volumes:
      - ../:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: docker-raect
